version: "3.7"
services:
  postgresDB:
    image: postgres:11-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: jcquevedo84
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/create.sql:/docker-entrypoint-initdb.d/1-create.sql
      - ./database/tables.sql:/docker-entrypoint-initdb.d/2-tables.sql
      - ./database/setup_data.sql:/docker-entrypoint-initdb.d/3-setup_data.sql
      - ./database/test_data.sql:/docker-entrypoint-initdb.d/4-test_data.sql
networks: 
  default:
    name: postgres-db